language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
branches:
  only:
    - blog-raw # 设置自动化部署的源码分支
before_install:
  - export TZ='Asia/Shanghai' # 设置时区, 下面 commit 要用
  - npm install -g hexo-cli
install:
  - npm install  # 安装依赖组件
before_script:
  # 设置github账户信息
  - git config --global user.name "Gal@Builder" #设置github用户名
  - git config --global user.email "galseraph@gmail.com" #设置github用户邮箱
  - cp Readme.md source/Readme.md # 添加 github Readme 文件
script:
  - hexo generate --silent # 静默执行命令
after_success:
  - sed -i "s/GITHUB_TOKEN/${GITHUB_TOKEN}/" _config.yml
  - sed -i "s/\":octocat:Site updated at {{ now('YYYY-MM-DD HH:mm:ss') }}.\"/\":beginner:Travis CI Auto Builder at `date +\"%Y-%m-%d %H:%M\"`.\"/" _config.yml
  - hexo deploy
# 收工提醒
notifications:
  email:
    recipients:
      - galaster@foxmail.com
    on_success: change
    on_failure: always