language: node_js
node_js:
  - "stable" # nodejs的版本
cache:
  directories:
    - node_modules
branches:
  only:
    - blog-raw # 设置自动化部署的源码分支
env:
 global:
   - GITHUB_PATH: github.com/GalAster/Galaster.github.io.git
before_install:
  - export TZ='Asia/Shanghai' # 设置时区, 下面 commit 要用
  - npm install -g hexo-cli
install:
  - npm install  # 安装依赖组件
  # - npm install hexo-deployer-git --save
before_script:
  # 设置github账户信息
  - git config --global user.name "Gal@Builder" #设置github用户名
  - git config --global user.email "galseraph@gmail.com" #设置github用户邮箱
  - cp Readme.md source/Readme.md # 添加 github Readme 文件
script:
  - hexo clean && hexo generate --silent # 静默执行命令
after_success:
  - mkdir .deploy && cd .deploy
  - git clone --depth 1 --branch master --single-branch "https://${GITHUB_TOKEN}@${GITHUB_PATH}" .
  - rm -rf ./* && cp -r ../public/* .
  - git add -A . && git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`:beginner:"
  - git branch -m master && git push -q -u origin master
# 收工提醒
notifications:
  email:
    recipients:
      - galaster@foxmail.com
    on_success: change
    on_failure: always