language: node_js
node_js:
  - "stable" # nodejs的版本
cache:
  directories:
    - node_modules
branches:
  only:
    - hexo # 设置自动化部署的源码分支
env:
 global:
   - GIT_NAME: Gal@Builder
   - GIT_MAIL: galseraph@gmail.com
before_install:
  # ssh 设定
  - cp build-tools/ssh.config ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_8e74c3062cc6_key -iv $encrypted_8e74c3062cc6_iv
    -in build-tools/git_rsa.enc -out ~/.ssh/git_rsa -d
  - chmod 600 ~/.ssh/git_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/git_rsa
install:
  - npm install -g hexo-cli
  - npm install  # 安装依赖组件
  - cp Readme.md source/Readme.md # 添加 github Readme 文件
  - sed -i "s~:octocat:~:beginning:~" _config.yml # 卖萌
before_script:
  # 设置github账户信息
  - git config --global user.name "${GIT_NAME}" #设置github用户名
  - git config --global user.email "${GIT_MAIL}" #设置github用户邮箱
  - export TZ='Asia/Shanghai' # deploy commit 会用到
script:
  - hexo generate －deploy